apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  clusterIP: None
  selector:
    app: node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
  namespace: simulation
spec:
  serviceName: node
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: llamerada/colonio-sim-node:dev-00
        command: ["/simulations"]
        args: ["sphere", "--seed-url", "ws://seed.simulation.svc.cluster.local:8080/simulate"]
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "100m"
